import {
  TextAlignStart,
  Hash,
  CircleArrowDown,
  List,
  CircleDashed,
  CalendarDays,
  UserRound,
  Paperclip,
  SquareCheckBig,
  Link,
  AtSign,
  Phone,
  Sigma,
  MoveUpRight,
  Search,
  Clock3,
  CircleUser,
  SquareMousePointer,
  MapPin,
} from "lucide-react";

export const COLUMN_TYPES = [
  { value: "text", label: "Text", icon: TextAlignStart },
  { value: "number", label: "Number", icon: Hash },
  { value: "select", label: "Select", icon: CircleArrowDown },
  { value: "multi_select", label: "Multi-select", icon: List },
  { value: "status", label: "Status", icon: CircleDashed },
  { value: "date", label: "Date", icon: CalendarDays },
  { value: "person", label: "Person", icon: UserRound },
  { value: "files", label: "Files & media", icon: Paperclip },
  { value: "checkbox", label: "Checkbox", icon: SquareCheckBig },
  { value: "url", label: "URL", icon: Link },
  { value: "email", label: "Email", icon: AtSign },
  { value: "phone", label: "Phone", icon: Phone },
  { value: "formula", label: "Formula", icon: Sigma },
  { value: "relation", label: "Relation", icon: MoveUpRight },
  { value: "rollup", label: "Rollup", icon: Search },
  { value: "created_time", label: "Created time", icon: Clock3 },
  { value: "created_by", label: "Created by", icon: CircleUser },
  { value: "last_edited_time", label: "Last edited time", icon: Clock3 },
  { value: "last_edited_by", label: "Last edited by", icon: CircleUser },
  { value: "button", label: "Button", icon: SquareMousePointer },
  { value: "place", label: "Place", icon: MapPin },
  { value: "id", label: "ID", icon: null, muted: true },
];
